### XGBoost (Extreme Gradient Boosting)

XGBoost es una implementación optimizada y distribuida del algoritmo de "gradient boosting" diseñada para ser altamente eficiente, flexible y portable. Ha ganado una inmensa popularidad debido a su excepcional rendimiento y velocidad en una amplia gama de tareas de aprendizaje supervisado, tanto para problemas de clasificación como de regresión.

**¿Cómo funciona?**
XGBoost se basa en la idea de construir una secuencia de modelos débiles (generalmente árboles de decisión, específicamente árboles de regresión), donde cada nuevo árbol intenta corregir los errores de los árboles anteriores. Es un algoritmo de "boosting" que mejora la predicción sumando los resultados de múltiples modelos.

### Paquete necesario
Es necesario instalar xgboost
```cmd
  pip install xgboost
```

### Python
```python
  import xgboost as xgb

  # Para regresión
  xgb_reg = xgb.XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
  )
  
  # Para Clasificación
  model = xgb.XGBClassifier(
    n_estimators=100,           
    learning_rate=0.1,          
    max_depth=3,                
    random_state=42
)
```




In [1]:
!pip install xgboost

In [2]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
import xgboost as xgb
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, matthews_corrcoef, confusion_matrix

In [4]:

wine = load_wine()
X = wine.data
y = wine.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)


# Inicializar y entrenar el modelo XGBoost
# xgb.XGBClassifier para problemas de clasificación
model = xgb.XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

model.fit(X_train, y_train)

print("\n XGBoost entrenado exitosamente.")

# Realizar predicciones en el conjunto de prueba
y_pred = model.predict(X_test)

# Evaluar el rendimiento del modelo
mcc = matthews_corrcoef(y_test, y_pred)
print(f"MCC del modelo XGBoost: {mcc:.4f}")

print("\nReporte de Clasificación:\n")
print(classification_report(y_test, y_pred, target_names=wine.target_names))

print("\nMatriz de Confusión:\n")
print(confusion_matrix(y_test, y_pred))


 XGBoost entrenado exitosamente.
MCC del modelo XGBoost: 1.0000

Reporte de Clasificación:

              precision    recall  f1-score   support

     class_0       1.00      1.00      1.00        18
     class_1       1.00      1.00      1.00        21
     class_2       1.00      1.00      1.00        15

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54


Matriz de Confusión:

[[18  0  0]
 [ 0 21  0]
 [ 0  0 15]]
